name: Build and deploy Node.js app to Azure Web App - cicdicull

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build --if-present

            - name: Zip dist folder for deployment
              run: zip -r dist.zip ./dist/cicdtest/browser

            - name: Upload dist artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                  name: node-app
                  path: dist.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                  name: node-app

            - name: Unzip dist artifact for deployment
              run: unzip dist.zip

            - name: "Deploy to Azure Web App"
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "cicdicull"
                  slot-name: "Production"
                  package: .
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0BF45D2637E54BABA39D39DF5D9C16DA }}
